### ISSUE TITLE
擴充套件目前無法使用

### ISSUE THREAD

**Issue by alexchiu100014** [stevenyomi/copymanga#75]
網頁可以正常進入
但是Mihon無法載入漫畫

**Comment by simplified-world** [comment]
我的可以正常使用。
我碰到的无法加载漫画的情况是，如果启用在登陆状态下搜索漫画，那不登陆就无法加载漫画

**Comment by simplified-world** [comment]
> 網頁可以正常進入 但是Mihon無法載入漫畫
我的可以正常使用。
我碰到的无法加载漫画的情况是，如果启用在登陆状态下搜索漫画，那不登陆就无法加载漫画

**Comment by simplified-world** [comment]
> 網頁可以正常進入 但是Mihon無法載入漫畫


我的可以正常使用。
我碰到的无法加载漫画的情况是，如果启用在登陆状态下搜索漫画，那不登陆就无法加载漫画

**Comment by alexchiu100014** [comment]
![Screenshot_20240402-185314](https://github.com/stevenyomi/copymanga/assets/48598830/46cd4838-3803-4c23-abf1-070b738081ac)

**Comment by simplified-world** [comment]
> ![Screenshot_20240402-185314](https://private-user-images.githubusercontent.com/48598830/318750523-46cd4838-3803-4c23-abf1-070b738081ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNTU1NzgsIm5iZiI6MTcxMjA1NTI3OCwicGF0aCI6Ii80ODU5ODgzMC8zMTg3NTA1MjMtNDZjZDQ4MzgtMzgwMy00YzIzLWFiZjEtMDcwYjczODA4MWFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDEwNTQzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwYzc2N2FjYTE0ZWQ4NGIxODVmZTFkMDA2ZjY5MmE5ZTY3YWFjMDVhZGQxOWU2ZjNlOGRkNTU1ZTQ0MTFhNTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7HZfnwbAdFvlwFc4D70g_L8ndF_9ebSY2TH3Q8M7EU)


那我就不清楚了，而且刚才我又试了一下，我之前碰到的情况也没出现，直接是正常加载。

**Comment by simplified-world** [comment]
> 網頁可以正常進入 但是Mihon無法載入漫畫


我看了一下，我用的是1.4.52，可能是这个原因？

**Comment by alexchiu100014** [comment]
> > 網頁可以正常進入 但是Mihon無法載入漫畫
> 
> 我看了一下，我用的是1.4.52，可能是这个原因？

1.4.52不是Tachidesk專用嗎？

**Comment by simplified-world** [comment]
> > > 網頁可以正常進入 但是Mihon無法載入漫畫
> > 
> > 
> > 我看了一下，我用的是1.4.52，可能是这个原因？
> 
> 1.4.52不是Tachidesk專用嗎？


mihon也可以用的，这两个是一样的软件，大概就是鲁迅和周树人的区别

**Comment by alexchiu100014** [comment]
> > 網頁可以正常進入 但是Mihon無法載入漫畫
> 
> 我看了一下，我用的是1.4.52，可能是这个原因？

下了
還是一樣

**Comment by simplified-world** [comment]
> > > 網頁可以正常進入 但是Mihon無法載入漫畫
> > 
> > 
> > 我看了一下，我用的是1.4.52，可能是这个原因？
> 
> 下了 還是一樣


或许把章末吐槽页选项也打开能加载，我下载最新版本后再次碰到了无法加载的问题，依然是打开了在登陆状态下搜索漫画却没有登陆，但是我启用章末吐槽页后可以加载。
如果这还是无法解决问题，那只能恕我无能为力了朋友。

**Comment by stevenyomi** [comment]
具体是怎么无法载入，章节目录能加载出来吗？另外请在高级（进阶）设置里把崩溃日志（当机记录）分享到这里。

**Comment by alexchiu100014** [comment]
> 具体是怎么无法载入，章节目录能加载出来吗？另外请在高级（进阶）设置里把崩溃日志（当机记录）分享到这里。

具體情況是
甚麼都載入不了
[mihon_crash_logs.txt](https://github.com/stevenyomi/copymanga/files/14836699/mihon_crash_logs.txt)

**Comment by alexchiu100014** [comment]
![Screenshot_20240402-203937~2](https://github.com/stevenyomi/copymanga/assets/48598830/651e5b9b-3df4-4704-9ef7-3b196f392164)

**Comment by 1265775896** [comment]
1.4.52版本，Tachidesk插件，4月1日网站更新后就无法连接

**Comment by bearpool** [comment]
我也遇到同样的问题，但同设备的网页报错error，然后发现mangacopy.com当天域名过期就没管了，这两天发现切换了代理的节点就正常了……

**Comment by simplified-world** [comment]
> 我也遇到同样的问题，但同设备的网页报错error，然后发现mangacopy.com当天域名过期就没管了，这两天发现切换了代理的节点就正常了……


我今天也是，换个节点就可以用了

**Comment by alexchiu100014** [comment]
> > 我也遇到同样的问题，但同设备的网页报错error，然后发现mangacopy.com当天域名过期就没管了，这两天发现切换了代理的节点就正常了……
> 
> 我今天也是，换个节点就可以用了

你們換的什麼節點
我全換了還是沒用（

**Comment by 1265775896** [comment]
> 我也遇到同样的问题，但同设备的网页报错error，然后发现mangacopy.com当天域名过期就没管了，这两天发现切换了代理的节点就正常了……

我的tachidesk直接建在服务器上，而服务器直接访问mangacopy是没问题的，就插件不行

**Comment by simplified-world** [comment]
> > > 我也遇到同样的问题，但同设备的网页报错error，然后发现mangacopy.com当天域名过期就没管了，这两天发现切换了代理的节点就正常了……
> > 
> > 
> > 我今天也是，换个节点就可以用了
> 
> 你們換的什麼節點 我全換了還是沒用（


实际上我用的可以看的和不可以看的都是香港节点……不知道什么原因
![微信图片_20240405141246](https://github.com/stevenyomi/copymanga/assets/148666838/a881b364-beff-4061-a377-76df4960027c)
![微信图片_20240405141300](https://github.com/stevenyomi/copymanga/assets/148666838/fd89b21c-547a-4772-bdf9-abb4da39367e)
![微信图片_20240405141307](https://github.com/stevenyomi/copymanga/assets/148666838/30b40a7a-a0e1-4ee2-a683-7c3c182a7254)
![微信图片_20240405141314](https://github.com/stevenyomi/copymanga/assets/148666838/2e0eed34-c555-4b04-9c5b-9a3576237324)
重启之后就显示加载失败了
![微信图片_20240405141310](https://github.com/stevenyomi/copymanga/assets/148666838/1660ad6f-bfcb-4a37-bd4c-0ea5ebc688bd)

**Comment by 1265775896** [comment]
1.4.52版本，Tachidesk插件，打开源以后持续加载
![image](https://github.com/stevenyomi/copymanga/assets/12364598/5164195f-c4b9-454a-a195-a5e4d896accf)

同时log疯狂无限反复刷
`2024-04-05T07:22:23.339051399Z 07:22:23.338 [DefaultDispatcher-worker-2] WARN notprivacysafe.graphql.execution.SimpleDataFetcherExceptionHandler -- Exception while fetching data (/fetchSourceManga) : 参数已更新，请重启应用
2024-04-05T07:22:23.339093497Z java.io.IOException: 参数已更新，请重启应用
2024-04-05T07:22:23.339099399Z  at eu.kanade.tachiyomi.extension.zh.copymanga.JsonKt.parseAs(Unknown Source)
2024-04-05T07:22:23.339104218Z  at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga.popularMangaParse(Unknown Source)
2024-04-05T07:22:23.339108716Z  at eu.kanade.tachiyomi.source.online.HttpSource$fetchPopularManga$1.invoke(HttpSource.kt:128)
2024-04-05T07:22:23.339112584Z  at eu.kanade.tachiyomi.source.online.HttpSource$fetchPopularManga$1.invoke(HttpSource.kt:127)
2024-04-05T07:22:23.339116601Z  at eu.kanade.tachiyomi.source.online.HttpSource.fetchPopularManga$lambda$2(HttpSource.kt:127)
2024-04-05T07:22:23.339120698Z  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:69)
2024-04-05T07:22:23.339124536Z  at rx.internal.operators.OnSubscribeDoOnEach$DoOnEachSubscriber.onNext(OnSubscribeDoOnEach.java:101)
2024-04-05T07:22:23.339145425Z  at eu.kanade.tachiyomi.network.OkHttpExtensionsKt$asObservable$1$requestArbiter$1.request(OkHttpExtensions.kt:39)
2024-04-05T07:22:23.339149633Z  at rx.Subscriber.setProducer(Subscriber.java:211)
2024-04-05T07:22:23.339153490Z  at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
2024-04-05T07:22:23.339157878Z  at rx.Subscriber.setProducer(Subscriber.java:205)
2024-04-05T07:22:23.339162056Z  at eu.kanade.tachiyomi.network.OkHttpExtensionsKt.asObservable$lambda$0(OkHttpExtensions.kt:59)
2024-04-05T07:22:23.339166586Z  at rx.Observable.unsafeSubscribe(Observable.java:10327)
2024-04-05T07:22:23.339170503Z  at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:41)
2024-04-05T07:22:23.339174310Z  at rx.internal.operators.OnSubscribeDoOnEach.call(OnSubscribeDoOnEach.java:30)
2024-04-05T07:22:23.339178207Z  at rx.Observable.unsafeSubscribe(Observable.java:10327)
2024-04-05T07:22:23.339192043Z  at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:48)
2024-04-05T07:22:23.339196672Z  at rx.internal.operators.OnSubscribeMap.call(OnSubscribeMap.java:33)
2024-04-05T07:22:23.339200990Z  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
2024-04-05T07:22:23.339205489Z  at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
2024-04-05T07:22:23.339209296Z  at rx.Observable.subscribe(Observable.java:10423)
2024-04-05T07:22:23.339213133Z  at rx.Observable.subscribe(Observable.java:10390)
2024-04-05T07:22:23.339218664Z  at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitOne(RxCoroutineBridge.kt:28)
2024-04-05T07:22:23.339222781Z  at suwayomi.tachidesk.manga.impl.util.lang.RxCoroutineBridgeKt.awaitSingle(RxCoroutineBridge.kt:22)
2024-04-05T07:22:23.339226668Z  at eu.kanade.tachiyomi.source.CatalogueSource$DefaultImpls.getPopularManga(CatalogueSource.kt:27)
2024-04-05T07:22:23.339230456Z  at eu.kanade.tachiyomi.source.online.HttpSource.getPopularManga(HttpSource.kt:28)
2024-04-05T07:22:23.339234603Z  at suwayomi.tachidesk.graphql.mutations.SourceMutation$fetchSourceManga$1.invokeSuspend(SourceMutation.kt:123)
2024-04-05T07:22:23.339238741Z  at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-04-05T07:22:23.339242709Z  at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
2024-04-05T07:22:23.339246646Z  at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
2024-04-05T07:22:23.339250644Z  at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
2024-04-05T07:22:23.339254440Z  at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
2024-04-05T07:22:23.339258298Z  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
2024-04-05T07:22:23.339262546Z  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
2024-04-05T07:22:23.339298122Z  at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
2024-04-05T07:22:23.339306749Z Caused by: rx.exceptions.OnErrorThrowable$OnNextValue: OnError while emitting onNext value: okhttp3.Response.class
2024-04-05T07:22:23.339310686Z  at rx.exceptions.OnErrorThrowable.addValueAsLastCause(OnErrorThrowable.java:118)
2024-04-05T07:22:23.339314523Z  at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:73)
2024-04-05T07:22:23.339318380Z  ... 29 common frames omitted`

其他源皆正常，服务器部署，ip能访问mangacopy.com

**Comment by alexchiu100014** [comment]
我的情況
Sorayomi是正常的
但是Mihon和J2K無法使用（手機上目前有安裝的）

**Comment by alexchiu100014** [comment]
好吧
連Sorayomi都壞了
`Received invaild status code: 404`
目前是備份回復的可以看
新加的會404

**Comment by alexchiu100014** [comment]
關閉Issue
因為他自己好了
我也不知道為什麼

**Comment by aimeidaer** [comment]
> 好吧 連Sorayomi都壞了 `Received invaild status code: 404` 目前是備份回復的可以看 新加的會404

是的 我也是这个情况，请问你解决了吗？

**Comment by alexchiu100014** [comment]
> > 好吧 連Sorayomi都壞了 `Received invaild status code: 404` 目前是備份回復的可以看 新加的會404
> 
> 是的 我也是这个情况，请问你解决了吗？

解決了
他自己好了
不知道為什麼

**Comment by alexchiu100014** [comment]
現在又壞了
Received invaild status code: 404
使用Suwayomi

**Comment by sfai05** [comment]
> 現在又壞了 Received invaild status code: 404 使用Suwayomi

I have the same issue on suwayomi.
Using
v1.4.52
 Tachidesk Preview 电脑/服务器兼容版（r1343 版本以上）
suwayomi/tachidesk:v1.1.1-r1566

**Comment by alexchiu100014** [comment]
ERROR從404變成500

**Comment by sfai05** [comment]
> > 現在又壞了 Received invaild status code: 404 使用Suwayomi
> 
> I have the same issue on suwayomi. Using v1.4.52 Tachidesk Preview 电脑/服务器兼容版（r1343 版本以上） suwayomi/tachidesk:v1.1.1-r1566

I tired differnt combination of suwayomi and the copymanga extention, here's a working one -
suwayomi/tachidesk:v1.1.1 ( current stable )
copymanga:v1.4.52 Tachidesk 电脑/服务器兼容版

**Comment by alexchiu100014** [comment]
> > > 現在又壞了 Received invaild status code: 404 使用Suwayomi
> > 
> > 
> > I have the same issue on suwayomi. Using v1.4.52 Tachidesk Preview 电脑/服务器兼容版（r1343 版本以上） suwayomi/tachidesk:v1.1.1-r1566
> 
> I tired differnt combination of suwayomi and the copymanga extention, here's a working one - suwayomi/tachidesk:v1.1.1 ( current stable ) copymanga:v1.4.52 Tachidesk 电脑/服务器兼容版

I think I finally know what happened to my server
It just stuck on the page asking me to choose which route I want to use.
And because I'm using Docker, I have no way to done this.

**Comment by sfai05** [comment]
> > 
> 
> I think I finally know what happened to my server It just stuck on the page asking me to choose which route I want to use. And because I'm using Docker, I have no way to done this.

I am hosting on Docker as well, currently on suwayomi/tachidesk:v1.1.1-r1586
I don't find any issue after switching to the extension version "copymanga:v1.4.52 Tachidesk 电脑/服务器兼容版"
So you mean that your issue is on suwayomi but not about the copymanga extension ?
