### ISSUE TITLE
TachiyomiAZ该插件无效

### ISSUE THREAD

**Issue by Mortalit** [stevenyomi/copymanga#77]
webview能打开网站

**Comment by stevenyomi** [comment]
提供的信息太少。

**Comment by rxvincent** [comment]
同样的情况，在logcat中会提示

failed to update app version
java.io.IOException: 加载失败，如果重试无效请在 GitHub 上反馈
 at eu.kanade.tachiyomi.extension.zh.copymanga.JsonKt.parseAs(Json.kt:27)
 at eu.kanade.tachiyomi.extension.zh.copymanga.VersionUpdaterKt.updateVersion(VersionUpdater.kt:28)
 at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga$client$1.invoke(CopyManga.kt:113)
 at eu.kanade.tachiyomi.extension.zh.copymanga.CopyManga$client$1.invoke(CopyManga.kt:113)
 at kotlin.concurrent.ThreadsKt$thread$thread$1.run(Thread.kt:30)

因为目前只有AZ可以导入JSON格式的备份，这个功能对于将拷贝中的订阅迁移至tachiyomi系的阅读器十分重要。

**Comment by rxvincent** [comment]
其他支持json导入的旧版都没法显示插件列表，也不能识别已安装的插件了
